### PR TITLE
David Shaw - Adding Resolver

### PR DESCRIPTION
**Pull request by ds2000**
Both files in one commit.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Thanks! Spec tests are probably failing due to changes in the Travis infrastructure. We've seen this before. I'll see what I can do about it and add the fixes to this pull request.

**Comment by ds2000** [comment]
Great, thanks for the original too.

Dave

**Comment by anders-larsson** [comment]
Hi @ds2000. I did some changes to your initial commit:
* Remove extraneous whitespaces after added parameter (caused puppet-lint to fail)
* Moved realization of resolver further down and added validate_hash (to allow basic spec tests)
* Basic spec tests added for it
 
The remaining commits are to fix other stuff and enable spec tests for Puppetv5 and Puppetv6. If everything looks good on your side (and spec tests actually succeed) I'll merge this.

Best Regards

**Review by ds2000 — COMMENTED** [review]
Looks good to me :)

**Comment by anders-larsson** [comment]
Thank you for your contribution @ds2000 !

Have a nice day!

**Comment by anders-larsson** [comment]
Released v1.1.0.

**Pull request merged**
